language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

dist: trusty

git:
  depth: 1

addons:
    apt:
      packages:
        - mesa-common-dev
        - libgle3-dev
        - libsdl2-dev
        - libsdl2-image-dev
        - libsdl2-ttf-dev
        - liballegro5-dev
        - libfreetype6-dev

before_install:
  # download oglft
  - wget http://downloads.sourceforge.net/project/oglft/oglft/Version%200.9/oglft-0.9.tar.gz && tar -xvf oglft-0.9.tar.gz
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install sdl2 sdl2_image sdl2_ttf allegro freetype; fi
  - if [ $TRAVIS_OS_NAME" == osx ];  cd oglft-0.9 && ./configure && make && sudo make install && cd ..; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then cd oglft-0.9 && ./configure --prefix=/usr && make && sudo make install && cd ..; fi

before_script:
  - cmake -DENABLE_SDL_CONTRIB=ON -DENABLE_OPENGL_CONTRIB=ON .

script:
  - make
  - sudo make install

notifications:
  irc: "irc.freenode.org#fife"
  email: false
