language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

dist: trusty

git:
  depth: 1

addons:
    apt:
      packages:
        - subversion
        - mesa-common-dev
        - libsdl2-dev
        - libsdl2-image-dev
        - libsdl2-ttf-dev
        - libfreetype6-dev
        # Disallowed, have to be installed manually
        #- liballegro5-dev
        #- libgle3-dev

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -qq update && sudo apt-get install -y libgle3-dev liballegro5-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install subversion sdl2 sdl2_image sdl2_ttf allegro freetype; fi
  - svn checkout svn://svn.code.sf.net/p/oglft/code/trunk oglft-code
  - if [ $TRAVIS_OS_NAME == osx ]; then cd oglft-0.9 && ./configure CPPFLAGS="$(freetype-config --cflags)" && make && sudo make install && cd ..; fi
  - cd oglft-code
  # Patch CMakeLists.txt dont load shipped CMake Modul to load FreeType, its provided by CMake and able to find FreeType.
  - sed -in '4d' CMakeLists.txt
  # Also include Freetype
  - sed -in '6aif(Freetype_FOUND)' CMakeLists.txt
  - sed -in '7aINCLUDE_DIRECTORIES(${FREETYPE_INCLUDE_DIRS})' CMakeLists.txt
  - sed -in '8aendif(Freetype_FOUND)' CMakeLists.txt
  - cmake . && make && sudo make install && cd ..

before_script:
  - cmake -DENABLE_SDL_CONTRIB=ON -DENABLE_OPENGL_CONTRIB=ON .

script:
  - make
  - sudo make install

notifications:
  irc: "irc.freenode.org#fife"
  email: false
