# Build worker image (VM template)
image: Visual Studio 2022

# scripts that are called at very beginning, before repo cloning
init:
  - date /T & time /T
  - git config --global core.autocrlf input
  - cmake --version
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

clone_depth: 5

version: '{build}'

platform:
  - x86
 # - x64

configuration:
  - Release
  #- Debug

environment:
  matrix:
    - generator: "Visual Studio 17 2022"
    - generator: "Visual Studio 16 2019"
    - generator: "Visual Studio 15 2017"
    #- generator: "MinGW Makefiles"

matrix:
  fast_finish: true

#cache:
#  - C:\projects\fifechan-dependencies\downloads
#  - C:\projects\fifengine-dependencies\includes

install:
  # get dependencies
  - cmake dependencies -G "%generator%" -B../fifechan-dependencies/build
  - cmake --build ../fifechan-dependencies/build --target ALL_BUILD --config %configuration%
  # show dependency folders
  - dir ..\fifechan-dependencies
  - dir ..\fifechan-dependencies\downloads
  - dir ..\fifechan-dependencies\includes /s

#before_build:
  # git sh.exe conflicts with MinGW makefiles
  #- if "%generator%"=="MinGW Makefiles" (set "PATH=%PATH:C:\Program Files\Git\usr\bin;=%")

build_script:
  - dir
  # create folder for an out-of-source-tree build: "c:\projects\build"
  - cd..
  - mkdir build
  - cd build
  # generate build script - SHARED
  - >
    cmake ..\fifechan
    -G "%generator%"
    -DCMAKE_BUILD_TYPE=%configuration%
    -DCMAKE_INSTALL_PREFIX="c:/fifechan/install-shared"
  # build
  - cmake --build . --target ALL_BUILD --config %configuration%
  # install
  - cmake --build . --target INSTALL --config %configuration%
  # generate build script - STATIC
  - >
    cmake ..\fifechan
    -G "%generator%"
    -DCMAKE_BUILD_TYPE=%configuration%
    -DCMAKE_INSTALL_PREFIX="c:/fifechan/install-static"
    -DBUILD_FIFECHAN_SHARED=OFF
    -DBUILD_FIFECHAN_OPENGL_SHARED=OFF
    -DBUILD_FIFECHAN_SDL_SHARED=OFF
  # build
  - cmake --build . --target ALL_BUILD --config %configuration% -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  # install
  - cmake --build . --target INSTALL --config %configuration%

after_build:
  # show defined env variables
  #- set
  - if "%generator%"=="Visual Studio 15 2017" (set COMPILER="VC15")
  - if "%generator%"=="Visual Studio 16 2019" (set COMPILER="VC16")
  - if "%generator%"=="Visual Studio 17 2022" (set COMPILER="VC17")
  - if "%generator%"=="MinGW Makefiles"  (set COMPILER="MinGW")
  # package artifact folder (shared library)
  - cd c:\fifechan\install-shared
  - mkdir bin
  - move c:\fifechan\install-shared\lib\*.dll c:\fifechan\install-shared\bin
  - 7z a -tzip -mx9 "%APPVEYOR_BUILD_FOLDER%\fifechan-shared-%APPVEYOR_BUILD_VERSION%-%COMPILER%-%platform%.zip"
  - appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\fifechan-shared-%APPVEYOR_BUILD_VERSION%-%COMPILER%-%platform%.zip"
  # publish an additional unversionized artifact (for being able to directly link the latest build)
  - copy "%APPVEYOR_BUILD_FOLDER%\fifechan-shared-%APPVEYOR_BUILD_VERSION%-%COMPILER%-%platform%.zip" "%APPVEYOR_BUILD_FOLDER%\fifechan-shared-%COMPILER%-%platform%.zip"
  - appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\fifechan-shared-%COMPILER%-%platform%.zip"
  # package artifact folder (static library)
  - cd c:\fifechan\install-static
  - 7z a -tzip -mx9 "%APPVEYOR_BUILD_FOLDER%\fifechan-static-%APPVEYOR_BUILD_VERSION%-%COMPILER%-%platform%.zip"
  - appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\fifechan-static-%APPVEYOR_BUILD_VERSION%-%COMPILER%-%platform%.zip"
  # publish an additional unversionized artifact (for being able to directly link the latest build)
  - copy "%APPVEYOR_BUILD_FOLDER%\fifechan-static-%APPVEYOR_BUILD_VERSION%-%COMPILER%-%platform%.zip" "%APPVEYOR_BUILD_FOLDER%\fifechan-static-%COMPILER%-%platform%.zip"
  - appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\fifechan-static-%COMPILER%-%platform%.zip"

artifacts:
  - path: '\fifechan-static-*.zip'
    name: Static-Library
  - path: '\fifechan-shared-*.zip'
    name: Shared-Library

# deploy to Github Releases on tag push
deploy:
  provider: GitHub
  release: 'Fifechan $(APPVEYOR_REPO_TAG_NAME)'
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: '[**Changelog**](https://github.com/fifengine/fifechan/blob/master/CHANGELOG.md)'
  artifact: Static-Library, Shared-Library
  draft: false
  prerelease: false
  force_update: true               # overwrite files of existing release on GitHub
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
  auth_token:                      # encrypted token from GitHub
    secure: PklA532IBf2s4paPOoYBviN4cz1Dew9+Bce0aO6VaINDMCxDLRiNGeg3Jchaw03C
    
